import { PostCommentsSectionBase } from './PostCommentsSectionBase'

export function PostImageViewerCommentsSection({
  t,
  comments,
  commentsLoading,
  commentSending,
  commentError,
  commentText,
  setCommentText,
  commentImages,
  commentVideo,
  commentAudio,
  commentDocuments,
  commentUploading,
  showGifPicker,
  setShowGifPicker,
  gifQuery,
  setGifQuery,
  gifResults,
  gifLoading,
  commentTextareaRef,
  commentImageInputRef,
  commentVideoInputRef,
  commentAudioInputRef,
  commentDocInputRef,
  handleCommentImageSelect,
  handleCommentVideoSelect,
  handleCommentAudioSelect,
  handleCommentDocSelect,
  handleGifSearch,
  handleSelectGif,
  removeCommentImage,
  removeCommentVideo,
  removeCommentAudio,
  removeCommentDoc,
  handleSendComment,
  handleToggleCommentLike,
  handleFeedCommentLikeMouseEnter,
  handleFeedCommentLikeMouseLeave,
  setCommentReactionsModalCommentId,
  setCommentReactionsModalInitialTab,
  setShowCommentReactionsModal,
  replyToComment,
  startReplyToComment,
  cancelReplyToComment,
  expandAfterReply,
  onExpandAfterReplyConsumed,
  modalSurface = 'adaptive',
  stickyComposer = true,
  unifiedScroll = true,
}) {
  return (
    <PostCommentsSectionBase
      variant="modal"
      modalSurface={modalSurface}
      stickyComposer={stickyComposer}
      unifiedScroll={unifiedScroll}
      t={t}
      comments={comments}
      commentsLoading={commentsLoading}
      commentSending={commentSending}
      commentError={commentError}
      commentText={commentText}
      setCommentText={setCommentText}
      commentImages={commentImages}
      commentVideo={commentVideo}
      commentAudio={commentAudio}
      commentDocuments={commentDocuments}
      commentUploading={commentUploading}
      showGifPicker={showGifPicker}
      setShowGifPicker={setShowGifPicker}
      gifQuery={gifQuery}
      setGifQuery={setGifQuery}
      gifResults={gifResults}
      gifLoading={gifLoading}
      commentTextareaRef={commentTextareaRef}
      commentImageInputRef={commentImageInputRef}
      commentVideoInputRef={commentVideoInputRef}
      commentAudioInputRef={commentAudioInputRef}
      commentDocInputRef={commentDocInputRef}
      handleCommentImageSelect={handleCommentImageSelect}
      handleCommentVideoSelect={handleCommentVideoSelect}
      handleCommentAudioSelect={handleCommentAudioSelect}
      handleCommentDocSelect={handleCommentDocSelect}
      handleGifSearch={handleGifSearch}
      handleSelectGif={handleSelectGif}
      removeCommentImage={removeCommentImage}
      removeCommentVideo={removeCommentVideo}
      removeCommentAudio={removeCommentAudio}
      removeCommentDoc={removeCommentDoc}
      handleSendComment={handleSendComment}
      handleToggleCommentLike={handleToggleCommentLike}
      handleFeedCommentLikeMouseEnter={handleFeedCommentLikeMouseEnter}
      handleFeedCommentLikeMouseLeave={handleFeedCommentLikeMouseLeave}
      setCommentReactionsModalCommentId={setCommentReactionsModalCommentId}
      setCommentReactionsModalInitialTab={setCommentReactionsModalInitialTab}
      setShowCommentReactionsModal={setShowCommentReactionsModal}
      replyToComment={replyToComment}
      startReplyToComment={startReplyToComment}
      cancelReplyToComment={cancelReplyToComment}
      expandAfterReply={expandAfterReply}
      onExpandAfterReplyConsumed={onExpandAfterReplyConsumed}
    />
  )
}
