export const ACHIEVEMENT_CATEGORIES = [
  {
    id: 'learning',
    title: 'Học tập',
    description: 'Thành tựu khi hoàn thành bài học và tích lũy tiến độ.',
    items: [
      {
        id: 'first-lesson',
        name: 'Bước đầu tiên',
        icon: 'school',
        rarity: 'common',
        howTo: 'Hoàn thành 1 bài học bất kỳ (Reading/Listening/Writing).',
        rewards: ['+50 XP', 'Huy hiệu “Bước đầu tiên”'],
        link: {
          label: 'Đi tới luyện tập',
          to: '/skills/reading',
        },
      },
      {
        id: 'streak-7',
        name: 'Chuỗi 7 ngày',
        icon: 'local_fire_department',
        rarity: 'uncommon',
        howTo: 'Học liên tiếp 7 ngày (mỗi ngày hoàn thành ít nhất 1 hoạt động).',
        rewards: ['+200 XP'],
      },
      {
        id: 'streak-30',
        name: 'Chuỗi 30 ngày',
        icon: 'whatshot',
        rarity: 'rare',
        howTo: 'Học liên tiếp 30 ngày.',
        rewards: ['+800 XP'],
      },
      {
        id: 'xp-1000',
        name: 'Thợ săn XP',
        icon: 'bolt',
        rarity: 'common',
        howTo: 'Tích lũy tổng cộng 1,000 XP.',
        rewards: ['+100 XP'],
      },
      {
        id: 'level-10',
        name: 'Lên cấp 10',
        icon: 'trending_up',
        rarity: 'uncommon',
        howTo: 'Đạt Level 10.',
        rewards: ['+300 XP'],
      },
    ],
  },
  {
    id: 'skills',
    title: 'Kỹ năng',
    description: 'Hoàn thành và nâng cao từng kỹ năng Reading/Listening/Writing.',
    items: [
      {
        id: 'reading-5',
        name: 'Reading Rookie',
        icon: 'menu_book',
        rarity: 'common',
        howTo: 'Hoàn thành 5 bài Reading.',
        rewards: ['+120 XP'],
      },
      {
        id: 'listening-5',
        name: 'Listening Rookie',
        icon: 'headphones',
        rarity: 'common',
        howTo: 'Hoàn thành 5 bài Listening.',
        rewards: ['+120 XP'],
      },
      {
        id: 'writing-5',
        name: 'Writing Rookie',
        icon: 'edit_note',
        rarity: 'common',
        howTo: 'Hoàn thành 5 bài Writing.',
        rewards: ['+120 XP'],
      },
      {
        id: 'perfect-score',
        name: 'Điểm tuyệt đối',
        icon: 'workspace_premium',
        rarity: 'rare',
        howTo: 'Đạt 100% điểm trong 1 bài bất kỳ.',
        rewards: ['+250 XP'],
      },
      {
        id: 'accuracy-90x5',
        name: 'Chuẩn xác',
        icon: 'verified',
        rarity: 'epic',
        howTo: 'Đạt accuracy ≥ 90% trong 5 bài liên tiếp.',
        rewards: ['+600 XP'],
      },
    ],
  },
  {
    id: 'vocab',
    title: 'Từ vựng & Ôn tập',
    description: 'Ghi nhớ từ mới và duy trì thói quen ôn tập.',
    items: [
      {
        id: 'vocab-50',
        name: 'Nhặt nhạnh từ mới',
        icon: 'collections_bookmark',
        rarity: 'common',
        howTo: 'Lưu 50 từ vựng vào sổ tay / flashcards.',
        rewards: ['+150 XP'],
      },
      {
        id: 'flashcard-7',
        name: 'Flashcard Streak',
        icon: 'style',
        rarity: 'uncommon',
        howTo: 'Ôn flashcards 7 ngày liên tiếp.',
        rewards: ['+250 XP'],
      },
      {
        id: 'recall-50',
        name: 'Nhớ dai',
        icon: 'psychology',
        rarity: 'rare',
        howTo: 'Trả lời đúng 50 flashcards liên tiếp.',
        rewards: ['+500 XP'],
      },
    ],
  },
  {
    id: 'quests',
    title: 'Nhiệm vụ & Thử thách',
    description: 'Hoàn thành quests/challenges để nhận thưởng XP.',
    items: [
      {
        id: 'quest-1',
        name: 'Quest Beginner',
        icon: 'flag',
        rarity: 'common',
        howTo: 'Hoàn thành 1 quest.',
        rewards: ['+80 XP'],
      },
      {
        id: 'quest-10',
        name: 'Quest Finisher',
        icon: 'emoji_events',
        rarity: 'uncommon',
        howTo: 'Hoàn thành 10 quests.',
        rewards: ['+300 XP'],
      },
      {
        id: 'daily-7',
        name: 'Daily Dominator',
        icon: 'calendar_month',
        rarity: 'rare',
        howTo: 'Hoàn thành daily quests 7 ngày liên tiếp.',
        rewards: ['+700 XP'],
      },
    ],
  },
  {
    id: 'community',
    title: 'Cộng đồng',
    description: 'Tương tác và đóng góp nội dung trong cộng đồng.',
    items: [
      {
        id: 'first-post',
        name: 'Bài viết đầu tiên',
        icon: 'edit_square',
        rarity: 'common',
        howTo: 'Đăng 1 bài viết bất kỳ.',
        rewards: ['+60 XP'],
        link: {
          label: 'Đi tới trang Home',
          to: '/home',
        },
      },
      {
        id: 'first-comment',
        name: 'Bình luận đầu tiên',
        icon: 'chat_bubble',
        rarity: 'common',
        howTo: 'Bình luận 1 lần vào bài viết.',
        rewards: ['+40 XP'],
      },
      {
        id: 'popular-post',
        name: 'Bài viết nổi bật',
        icon: 'trending_up',
        rarity: 'epic',
        howTo: 'Một bài viết đạt ≥ 50 likes.',
        rewards: ['+800 XP'],
      },
    ],
  },
  {
    id: 'social',
    title: 'Bạn bè & Chat',
    description: 'Kết nối, nhắn tin và tham gia nhóm.',
    items: [
      {
        id: 'first-friend',
        name: 'Người bạn đầu tiên',
        icon: 'person_add',
        rarity: 'common',
        howTo: 'Kết bạn thành công với 1 người.',
        rewards: ['+60 XP'],
      },
      {
        id: 'connector-10',
        name: 'Kết nối',
        icon: 'hub',
        rarity: 'uncommon',
        howTo: 'Có 10 bạn bè.',
        rewards: ['+200 XP'],
      },
      {
        id: 'group-join-5',
        name: 'Tham gia hội nhóm',
        icon: 'groups',
        rarity: 'uncommon',
        howTo: 'Tham gia 5 nhóm chat.',
        rewards: ['+250 XP'],
      },
    ],
  },
]

