// Subset of Material Symbols icon names used as suggestions.
// Đây KHÔNG phải full catalog Google, chỉ là các icon hay dùng cho gamification / học tập.
export const MATERIAL_ICON_SUGGESTIONS = [
  // Achievements / rewards
  'emoji_events',
  'workspace_premium',
  'military_tech',
  'trophy',
  'star',
  'stars',
  'grade',
  'verified',
  'verified_user',
  'workspace_premium',
  'medal',
  'diamond',
  'local_fire_department',
  'whatshot',
  'bolt',
  'flash_on',
  'electric_bolt',
  'celebration',
  'emoji_events',

  // Learning / study
  'school',
  'menu_book',
  'auto_stories',
  'import_contacts',
  'book_4',
  'quiz',
  'psychology',
  'psychology_alt',
  'lightbulb',
  'lightbulb_circle',
  'tips_and_updates',
  'translate',
  'language',
  'spellcheck',

  // Skills / tasks / progress
  'check_circle',
  'task_alt',
  'done_all',
  'checklist',
  'checklist_rtl',
  'progress_activity',
  'hourglass_top',
  'hourglass_bottom',
  'timeline',
  'leaderboard',
  'flag',
  'outlined_flag',
  'goal',

  // Social / community
  'groups',
  'group',
  'group_add',
  'person',
  'person_add',
  'supervisor_account',
  'hub',
  'forum',
  'chat',
  'chat_bubble',
  'chat_bubble_outline',
  'mark_unread_chat_alt',
  'alternate_email',
  'thumb_up',
  'favorite',

  // Quests / challenges / calendar
  'flag_circle',
  'explore',
  'explore_off',
  'map',
  'route',
  'assignment',
  'assignment_turned_in',
  'assignment_emoji',
  'sticky_note_2',
  'event',
  'event_available',
  'calendar_month',
  'schedule',

  // Misc nice-looking icons
  'insights',
  'bar_chart',
  'stacked_bar_chart',
  'donut_small',
  'egg_alt',
  'rocket_launch',
  'sports_esports',
  'extension',
  'auto_awesome',
  'sparkles',

  // Extra pool for search
  'emoji_emotions',
  'sentiment_satisfied',
  'sentiment_very_satisfied',
  'sentiment_very_dissatisfied',
  'sentiment_neutral',
  'mood',
  'mood_bad',
  'star_border',
  'star_half',
  'thumb_up_off_alt',
  'thumb_down',
  'thumb_down_off_alt',
  'favorite_border',
  'favorite',
  'heart_broken',
  'emoji_people',
  'emoji_nature',
  'emoji_food_beverage',
  'emoji_symbols',
  'emoji_transportation',

  // UI / navigation
  'home',
  'home_pin',
  'dashboard',
  'dashboard_customize',
  'menu',
  'menu_open',
  'apps',
  'more_horiz',
  'more_vert',
  'settings',
  'settings_suggest',
  'settings_applications',
  'tune',
  'filter_alt',
  'filter_list',
  'search',
  'sort',
  'view_list',
  'view_module',
  'view_agenda',

  // Files / content
  'note',
  'description',
  'article',
  'notes',
  'folder',
  'folder_open',
  'folder_shared',
  'cloud',
  'cloud_upload',
  'cloud_download',
  'upload_file',
  'download',
  'download_done',
  'drive_file_move',
  'drive_file_rename_outline',
  'content_copy',
  'content_paste',
  'content_cut',

  // Media / play
  'play_arrow',
  'play_circle',
  'pause',
  'pause_circle',
  'stop',
  'stop_circle',
  'replay',
  'skip_next',
  'skip_previous',
  'volume_up',
  'volume_off',
  'volume_down',
  'music_note',
  'music_video',

  // Devices / status
  'wifi',
  'wifi_off',
  'signal_cellular_alt',
  'battery_full',
  'battery_charging_full',
  'battery_5_bar',
  'brightness_high',
  'dark_mode',
  'light_mode',
  'airplanemode_active',
  'bluetooth',
  'devices',

  // Alerts
  'error',
  'warning',
  'warning_amber',
  'info',
  'priority_high',
  'report',
  'notification_important',
  'notifications',
  'notifications_active',
  'notifications_off',

  // Actions (edit/delete/share)
  'add',
  'add_circle',
  'add_box',
  'remove',
  'delete',
  'delete_forever',
  'edit',
  'edit_square',
  'edit_off',
  'share',
  'ios_share',
  'send',
  'open_in_new',
  'link',
  'link_off',

  // Time / history
  'history',
  'history_toggle_off',
  'schedule',
  'alarm',
  'alarm_on',
  'timer',
  'timer_10',
  'timer_off',

  // Location
  'place',
  'location_on',
  'location_searching',
  'near_me',
  'map',
  'explore',

  // Misc gamification-friendly icons
  'emoji_flags',
  'emoji_objects',
  'military_tech',
  'sports_martial_arts',
  'sports_score',
  'sports_kabaddi',
  'sports_handball',
  'casino',
  'stadium',
  'toll',
  'auto_graph',
  'insights',
  'trending_up',
  'trending_down',
]

